---
title: "regression_competition"
output: html_document
date: "2024-11-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Map of Madrid with points and color indicating prizes

```{r}
library(readxl)
data_train <- read_excel("Data/data_train.xlsx")
```

```{r}
#install.packages(c("ggplot2", "sf", "dplyr"))

# Load libraries
library(ggplot2)
library(sf)
library(dplyr)
```

```{r}
points_sf <- st_as_sf(data_train, coords = c("longitud", "latitud"), crs = 4326)
points_sf <- points_sf[order(points_sf$precio.house.m2), ]
# Download the map of Madrid (use a simple shapefile, for example)
madrid_map <- st_read("Data/madrid.geojson")

# Plot the map with the points colored by the 'value' variable
ggplot() +
  geom_sf(data = madrid_map, fill = "lightgray", color = "white") +  # Plot map
  geom_sf(data = points_sf, aes(color = precio.house.m2), size = 1.5) +  # Plot points
  scale_color_gradient(low = "#00C5CD", high = "red") +
  labs(title = "Spatial situation and price",
       x = "Longitude", y = "Latitude") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels


### Done with teh help of ChatGPT
```




